language: java

jdk:
  - oraclejdk8

#before_install:
#  cd carpetaDondeEstaElPOM #solo si no tienen el pom en el raíz del repositorio

notifications:
  email:
    recipients:
      - guidoagustinbeltrame@gmail.com
      - martu_007@hotmail.com
      - tessov.evgueni@hotmail.com
      - diego.meligrana@gmail.com
      - lucasnvp@gmail.com
    on_success: [change] # default: change | [always|never|change]
    on_failure: [always] # default: always | [always|never|change]

